name: Upload template zip to release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    name: Publish zip to release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync docker files
        run: |
          rm -rf /tmp/release
          mkdir /tmp/release
          cd src/
          rsync . -rv --exclude-from=.releaseignore --exclude-from=.gitignore /tmp/release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Print vars
        run: printenv