name: Publish image

on:
  release:
    types:
      - published

permissions:
  packages: write

jobs:
  publish:
    name: Publish docker image
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync docker files
        run: |
          rm -rf /tmp/release
          mkdir /tmp/release
          cd src/
          rsync . -rv --exclude-from=.releaseignore --exclude-from=.gitignore /tmp/release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: /tmp/release/
          tags: ghcr.io/${{ github.repository }}/app-light:v${{ github.event.release.tag_name }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}